listening-port=3478
tls-listening-port=5349
realm=chat.app
use-auth-secret
static-auth-secret=coturn_super_secret_auth_key
fingerprint
lt-cred-mech
stale-nonce=600
no-multicast-peers
no-cli
log-file=stdout
