-- Down Migration / Rollback Procedure for 20260801000000_init

DROP TABLE IF EXISTS "Setting" CASCADE;
DROP TABLE IF EXISTS "BlockedUser" CASCADE;
DROP TABLE IF EXISTS "Participant" CASCADE;
DROP TABLE IF EXISTS "Call" CASCADE;
DROP TABLE IF EXISTS "Reaction" CASCADE;
DROP TABLE IF EXISTS "Receipt" CASCADE;
DROP TABLE IF EXISTS "Attachment" CASCADE;
DROP TABLE IF EXISTS "Message" CASCADE;
DROP TABLE IF EXISTS "ConversationMember" CASCADE;
DROP TABLE IF EXISTS "Conversation" CASCADE;
DROP TABLE IF EXISTS "OneTimePreKey" CASCADE;
DROP TABLE IF EXISTS "SignedPreKey" CASCADE;
DROP TABLE IF EXISTS "IdentityKey" CASCADE;
DROP TABLE IF EXISTS "RefreshToken" CASCADE;
DROP TABLE IF EXISTS "Device" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

DROP TYPE IF EXISTS "CallStatus";
DROP TYPE IF EXISTS "CallType";
DROP TYPE IF EXISTS "DeliveryStatus";
DROP TYPE IF EXISTS "MessageType";
DROP TYPE IF EXISTS "ConversationType";
DROP TYPE IF EXISTS "Role";
